profiles/urls.py
from django.urls import path
from .import views

app_name="profiles"

urlpatterns = [
    path("<str:username>/",views.ProfileDetailView.as_view(),name="detail"),
    path("<str:username>/follow/",views.FollowView.as_view(),name="follow")
]

til/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace="feed")),
    path("profiles/",include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^search/', include('search.urls', namespace='search')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.

class Profile(models.Model):
    user= models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
        
        
    image = ImageField(upload_to='profiles')

    
    def __str__(self) :
        return self.user.username

@receiver(post_save,sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    

profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest

from feed.models import Post
from followers.models import Follower


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context


class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == "follow":
            # Follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # Unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ user.username }}{% endblock title %}

{% block body %}
<div class="rounded rounded-t-lg overflow-hidden shadow max-w-xs my-3">
  	<img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profile.image "100x100" crop="center" as im %}
            <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
	<div class="text-center px-3 pb-6 pt-2">
		<h3 class="text-black text-sm bold font-sans">{{ user.username }}</h3>
        {% if request.user.is_authenticated %}
            {% if request.user != user %}
                <div class="mt-3">
                    <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 text-xs inline-flex items-center js-follow" data-username="{{ user.username }}" data-action="{%  if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}" type="button">
                        <span class="mr-2 js-follow-text">
                            {%if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                            
                            
                            
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                </div>
            {% endif %}
        {% else %}
            <div class="mt-3 text-sm">Login to follow this user</div>
        {% endif %}
	</div>
  	<div class="flex justify-center pb-3 text-grey-dark">
      <div class="text-center mr-3 border-r pr-3">
        <h2>{{ total_posts }}</h2>
        <span>Posts</span>
      </div>
      <div class="text-center">
        <h2>{{ total_followers }}</h2>
        <span>Followers</span>
      </div>
  	</div>
</div>
{% endblock body %}