feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("myfeed/", views.MyFeed.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
   
]

til/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace="feed")),
    path("profiles/",include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^search/', include('search.urls', namespace='search')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

til/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title >{% block title %}QnA{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>
<body>

<!-- component is from https://tailwindcomponents.com/component/sidebar-navigation -->
<div class=" min-h-screen flex flex-row bg-gray-100">
  <div class=" rounded bg-black fixed h-screen flex flex-col  w-56  drop-shadow-2xl  overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
      <h1 class="font-serif font-bold text-3xl  text-white">QnA</h1>
    </div>
    <ul class=" flex flex-col py-4">
      <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
          <span class="text-sm font-medium">Home</span>
        </a>
      </li>

      <li>
        <a href="/search" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	">
          <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-search"></i></span>
          <span class="text-sm font-medium">Search</span>
        </a>
      </li>

      {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'feed:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	 js-toggle-modal">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-layer-plus"></i></span>
            <span class="text-sm font-medium">New question</span>
            </a>
        </li>

        <li>
          <a href="/myfeed" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-label"></i></span>
            <span class="text-sm font-medium">My Feed</span>
          </a>
        </li>

        <li>
            <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
            <span class="text-sm font-medium">Logout</span>
            </a>
        </li>
      {% else %}
        <li>
            <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-white hover:text-slate-400	">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
            <span class="text-sm font-medium">Login</span>
            </a>
        </li>
      {% endif %}
    </ul>
  </div>
  <div class="ml-56 pl-2 w-full">
    {% block body %}
        {% block content %}{% endblock %}
    {% endblock %}
  </div>


{% if request.user.is_authenticated %}
  <!-- component -->
  <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 hidden js-modal">
    <div class="bg-white rounded-lg w-1/2">
      <div class="flex flex-col items-start p-4">
        <div class="flex items-center w-full">
          <div class="text-gray-900 font-medium text-lg">New question</div>
      <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
        </svg>
        </div>
        <hr>
        <div class="w-full">
          <!-- <form action="#" class="js-post-form" method="get" role="form" enctype="multipart/form-data" >
            
            <input name='file' class="js-post-image" data-post-url="{% url 'feed:new_post' %}" type="file" name="img" multiple>
             
           </form> -->
          <textarea class="border-2 border-blue-500 my-4  js-post-text w-full" placeholder= "Enter your Post" rows="3" maxlength="240" data-post-url="{% url 'feed:new_post' %}"></textarea>
        </div>
        <hr>
        <div class="ml-auto"> 
          <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit" type="button">
              <span class="mr-2">Ask</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
              </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}


</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>
</html>