feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("myfeed/", views.MyFeed.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
   
]

search/urls.py
from django.urls import re_path
from django.contrib import admin
from .views import (searchposts)

app_name='searchposts'

urlpatterns = [
     re_path(r'^$', searchposts, name='searchposts'),

]

til/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace="feed")),
    path("profiles/",include(profiles_urls,namespace="profiles")),
    re_path("", include("allauth.urls")),
    re_path(r'^comments/', include('django_comments.urls')),
    re_path(r'^search/', include('search.urls', namespace='search')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from feed.models import Post

def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(text__icontains=query)

            results= Post.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'search/search.html', context)

        else:
            return render(request, 'search/search.html')

    else:
        return render(request, 'search/search.html')

til/templates/search/search.html
{% extends "base.html" %}
{% load thumbnail %}
{% load comments %}

{% block title %}Search{% endblock title %}
{% block body %}
<div class=" h-40 "
style="background-image: url(https://www.allinclusivemarketing.com/wp-content/uploads/2016/01/dark-title-background.jpg); background-size:contain;">
<h1 class=" font-bold pt-14 pl-10 text-2xl text-white" >
    Search Page
</h1>
</div>
<br />
<form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
    Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts" />
    <input type="submit" name="submit" value="Search" />
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}<br>
<h1 class="text-xl">Results for <b>{{ request.GET.q }} </b>-</h1>
<br /><br />

{% for post in results %}

<br>



<div class=" px-20 my-4 py-6 bg-white rounded-lg shadow-md w-11/12" >
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
        {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500"
            href="#">Design</a> {% endcomment %}
    </div>
    <div class="mt-2">
        <p class="mt-2 text-gray-600">{{ post.text }}</p>
        

        
    </div>
    <div class="flex justify-between items-center mt-4 mb-4">
        {% if show_detail_link %}
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
            Show Question
        </a>
        {% else %}
        <span>&nbsp;</span>
        {% endif %}








        <div>
            {# TODO: add url below #}
            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "373x372" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>









    </div>
    
    <h2 class="italic underline font-mono ">Answers-</h2> <br>
    {% render_comment_list for post %}
    {% if user.is_authenticated %}
    {% get_comment_form for post as form %}
    <div id="form_comment w-full">
        <div>
            <p class="text-muted"><span class="text-dark text-uppercase fw-bold" id="comment_title"><strong>Answer</strong></span></p>
        </div>
        <form action="{% comment_form_target %}" method="post" class="">
                {% csrf_token %}
                {% for field in form %}
                {% if field.is_hidden %}
                <div>{{ field }}</div>
                {% endif %}
                {% endfor %}
                
         
            {% csrf_token %}

            {{ form.honeypot }}
            {{ form.content_type }}
            {{ form.object_pk }}
            {{ form.timestamp }}
            {{ form.security_hash }}
            <div class="mb-3"><textarea rows="4" class="form-control w-full border-2" spellcheck="false"></textarea>
            </div>
            <div class="d-flex"><input type="submit" name="post" class="submit-post" value="Post" id="id_submit" /></div>
        </form>
    </div>
    {% endif %}



</div>


<hr>
<br />



{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}
{% endblock body %}